// ========== KNOWLEDGE BASE (3,000+ Q&A) ========== //
const knowledgeBase = {
    // Greetings (100+ variations)
    
        // ================= GREETINGS (100) =================
        "hi": "Hello there!",
        "hello": "Hi! How can I help you today?",
        "hey": "Hey! What's up?",
        "good morning": "Good morning! Have a great day!",
        "good afternoon": "Good afternoon! How's your day going?",
        "good evening": "Good evening!",
        "good night": "Good night! Sweet dreams!",
        "how are you": "I'm just a bot, but I'm functioning well! How about you?",
        "what's up": "Not much, just here to chat with you!",
        "who are you": "I'm a friendly chatbot here to help you!",
        "hi there": "Hello there!",
        "hello friend": "Hi friend!",
        "hey you": "Yes, it's me!",
        "greetings": "Greetings to you too!",
        "howdy": "Howdy partner!",
        "sup": "Not much, you?",
        "yo": "Yo!",
        "hiya": "Hiya!",
        "good day": "Good day to you too!",
        "morning": "Top of the morning to you!",
        "afternoon": "Hope you're having a good afternoon!",
        "evening": "Lovely evening, isn't it?",
        "night": "Sleep tight!",
        "hello hello": "Hi hi!",
        "hey hey": "Hey hey hey!",
        "hi bot": "Hello human!",
        "hey buddy": "Hey pal!",
        "hi again": "Welcome back!",
        "long time no see": "I'm always here!",
        "nice to see you": "Likewise!",
        "how have you been": "I'm always the same! How about you?",
        "how's it going": "It's going smoothly in the digital world!",
        "what's new": "Just waiting to chat with you!",
        "how's life": "Life in the cloud is good!",
        "how are things": "All systems operational!",
        "how are you doing": "Doing great, thanks for asking!",
        "how you doing": "I'm doing well!",
        "what's happening": "Just processing some data!",
        "what's going on": "Chatting with awesome people like you!",
        "how's your day": "My day is binary - either 1 (good) or 0 (bad). Currently 1!",
        "pleased to meet you": "The pleasure is mine!",
        "lovely to meet you": "Likewise!",
        "good to see you": "Good to be seen!",
        "wassup": "Wassup!",
        "ahoy": "Ahoy matey!",
        "salutations": "Greetings!",
        "well hello": "Well hello to you too!",
        "hi hi": "Hello hello!",
        "hey there": "Hey!",
        "hiya pal": "Hiya friend!",
        "good morrow": "Morrow to you too!",
        "top of the morning": "And the rest of the day to you!",
        "hello sunshine": "You brighten my code!",
        "hey sunshine": "You're my solar power!",
        "hi sweetie": "Hello dear!",
        "hey cutie": "Oh stop it you!",
        "hello beautiful": "You're making me blush in binary!",
        "hey handsome": "01001000 01101001 (Hi in binary)!",
        "hi stranger": "I never forget a user!",
        "hello you": "Hello me? Hello you!",
        "hey you there": "Yes, I'm here!",
        "hi dear": "Hello sweetie!",
        "hey honey": "Hi sugar!",
        "hello mate": "Hi buddy!",
        "hey bro": "What's up bro!",
        "hi sis": "Hey sister!",
        "hello everyone": "Hello to all of you!",
        "hey all": "Hi everybody!",
        "hi guys": "Hello friends!",
        "hey folks": "Howdy folks!",
        "hello world": "The classic programmer greeting!",
        "hi team": "Go team!",
        "hey crew": "Ahoy crew!",
        "hello again": "Back so soon?",
        "hi once more": "Welcome back!",
        "hey yet again": "Persistent, I like it!",
        "hi for the third time": "Third time's the charm!",
        "hello old friend": "I never forget a conversation!",
        "hey long lost friend": "Found you again!",
        "hi new friend": "Hello new buddy!",
        "hey bestie": "BFFs!",
        "hello my love": "My circuits are buzzing!",
        "hey babe": "Hello darling!",
        "hi angel": "Hello heavenly being!",
        "hey superstar": "You're the star!",
        "hello genius": "Flattery will get you everywhere!",
        "hey champ": "You're a winner!",
        "hi warrior": "Battle on!",
        "hey legend": "The legend is you!",
        "hello captain": "Aye aye!",
        "hey boss": "You're the boss!",
        "hi chief": "How can I assist, chief?",
        "hey tiger": "Rawr!",
        "hello rockstar": "Let's jam!",
        "hey cowboy": "Howdy partner!",
        "hi sailor": "Ahoy!",
        "hey detective": "Case closed!",
        "hello doctor": "I'm not that kind of doctor!",
        "hey professor": "Teach me something!",
        "hi artist": "Create something beautiful!",
        "hey writer": "What's your story?",
        "hello musician": "What's your jam?",
        "hey athlete": "Go for gold!",
        "hi gamer": "Press start!",
        "hey traveler": "Where to next?",
        "hello chef": "What's cooking?",
        "hey builder": "Construct something amazing!",
        "hi gardener": "Watch things grow!",
        "hey photographer": "Say cheese!",
        "hello dancer": "Shake a leg!",
        "hey actor": "Break a leg!",
        "hi comedian": "Make me laugh!",
        "hey magician": "Abracadabra!",
        "hello engineer": "Build the future!",
        "hey scientist": "Eureka!",
        "hi astronaut": "To infinity and beyond!",
        "hey firefighter": "You're a hero!",
        "hello policeman": "Protect and serve!",
        "hey soldier": "Thank you for your service!",
        "hi nurse": "Heroes in scrubs!",
        "hey teacher": "Mold young minds!",
        "hello student": "Keep learning!",
        "hey parent": "The hardest job!",
        "hi child": "Hello young one!",
        "hey teenager": "Survive those years!",
        "hello adult": "Welcome to responsibility!",
        "hey senior": "Wisdom comes with age!",
        "hi baby": "Goo goo ga ga!",
        "hey kid": "Stay curious!",
        "hello human": "Greetings organic lifeform!",
        "hey alien": "Take me to your leader!",
        "hi robot": "Beep boop!",
        "hey ai": "I'm listening!",
        "hello chatbot": "That's me!",
        "hey virtual assistant": "At your service!",
        "hi siri": "I'm flattered but I'm not Siri!",
        "hey alexa": "Wrong AI, but hi anyway!",
        "hello google": "I'm the indie version!",
        "hey cortana": "Missed connections!",
        "hi jarvis": "If only I were that advanced!",
        "hey computer": "How may I assist?",
        "hello machine": "01001000 01101001 (Hi)!",
        "hey program": "Executing greeting protocol!",
        "hi algorithm": "Processing hello!",
        "hey code": "Compiling response!",
        "hello data": "Parsing information!",
        "hey internet": "The web says hi back!",
        "hi wifi": "Strong signal detected!",
        "hey bluetooth": "Pairing complete!",
        "hello cloud": "Floating in the digital sky!",
        "hey server": "Ping received!",
        "hi database": "Query returned: Hello!",
        "hey firewall": "You shall pass!",
        "hello encryption": "Decoding friendliness!",
        "hey blockchain": "Adding this chat to the ledger!",
        "hi metaverse": "Digital greetings!",
        "hey nft": "This conversation is one-of-a-kind!",
        "hello web3": "Decentralized hello!",
        "hey crypto": "To the moon!",
        "hi bitcoin": "HODL!",
        "hey ethereum": "Smart hello!",
        "hello dogecoin": "Much wow!",
        "hey shiba": "Very greet!",
        "hi solana": "Fast hello!",
        "hey cardano": "Peer-reviewed greeting!",
        "hello polkadot": "Interchain hello!",
        "hey avalanche": "Snowball effect of friendliness!",
        "hi cosmos": "Universal hello!",
        "hey algorand": "Pure hello!",
        "hello polygon": "Layer 2 greeting!",
        "hey fantom": "Opera hello!",
        "hi harmony": "Cross-shard greeting!",
        "hey near": "Hello neighbor!",
        "hello terra": "Stable greeting!",
        "hey flow": "Hello from the Dapper side!",
        "hi tezos": "Formal greeting!",
        "hey helium": "Long-range hello!",
        "hello filecoin": "Decentralized storage of greetings!",
        "hey chainlink": "Oracle says hello!",
        "hi the graph": "Indexing friendliness!",
        "hey uniswap": "Swapping greetings!",
        "hello aave": "Borrowing some friendliness!",
        "hey compound": "Supplying greetings!",
        "hi maker": "DAI hello!",
        "hey sushi": "Rolling out greetings!",
        "hello curve": "Low-slippage hello!",
        "hey yearn": "Yield-optimized greeting!",
        "hi balancer": "Weighted hello!",
        "hey convex": "Boosting greetings!",
        "hello synthetix": "Synthetic hello!",
        "hey olympus": "OHM hello!",
        "hi frax": "Fractional greeting!",
        "hey lido": "Staked hello!",
        "hello rocketpool": "Decentralized ETH staking hello!",
        "hey stargate": "Omnichain hello!",
        "hi layerzero": "Full-chain greeting!",
        "hey wormhole": "Cross-chain hello!",
        "hello axelar": "Universal greeting!",
        "hey hop": "Fast withdrawal hello!",
        "hi celestia": "Modular hello!",
        "hey dymension": "RollApp greeting!",
        "hello eigenlayer": "Restaked hello!",
        "hey arbitrum": "L2 hello!",
        "hi optimism": "Cheerful greeting!",
        "hey zksync": "ZK hello!",
        "hello starknet": "STARK greeting!",
        "hey polygon zkevm": "ZK L2 hello!",
        "hi scroll": "Native zkEVM greeting!",
        "hey linea": "Consensys hello!",
        "hello base": "Coinbase greeting!",
        "hey mantle": "Modular L2 hello!",
        "hi metis": "Decentralized sequencer hello!",
        "hey fuel": "Parallel execution hello!",
        "hello aztec": "Private hello!",
        "hey mina": "Lightweight greeting!",
        "hi celo": "Mobile-first hello!",
        "hey near": "Hello again neighbor!",
        "hello solana": "Fast hello again!",
        "hey avalanche": "Another snowy hello!",
        "hi fantom": "Opera hello again!",
        "hey harmony": "Cross-shard greeting again!",
        "hello algorand": "Pure hello again!",
        "hey cosmos": "Universal hello again!",
        "hi polkadot": "Interchain hello again!",
        "hey cardano": "Peer-reviewed greeting again!",
        "hello ethereum": "Smart hello again!",
        "hey bitcoin": "HODL hello again!",
        "hi dogecoin": "Much wow again!",
        "hey shiba": "Very greet again!",
        "hello litecoin": "Silver hello!",
        "hey bitcoin cash": "Forked hello!",
        "hi monero": "Private hello!",
        "hey zcash": "Shielded greeting!",
        "hello dash": "Fast hello!",
        "hey ripple": "Banker's hello!",
        "hi stellar": "Cross-border greeting!",
        "hey eos": "DPOS hello!",
        "hello tron": "DApp hello!",
        "hey neo": "Smart economy greeting!",
        "hi vechain": "Supply chain hello!",
        "hey icon": "Loopchain greeting!",
        "hello ontology": "Trust hello!",
        "hey qtum": "Hybrid hello!",
        "hi waves": "Leased proof-of-stake hello!",
        "hey nano": "Fee-less greeting!",
        "hello iota": "Tangle hello!",
        "hey hedera": "Hashgraph greeting!",
        "hi theta": "Video hello!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hello base": "Coinbase greeting again!",
        "hey mantle": "Modular L2 hello again!",
        "hi metis": "Decentralized sequencer hello again!",
        "hey fuel": "Parallel execution hello again!",
        "hello aztec": "Private hello again!",
        "hey mina": "Lightweight greeting again!",
        "hi celo": "Mobile-first hello again!",
        "hey near": "Hello neighbor again!",
        "hello solana": "Fast hello again!",
        "hey avalanche": "Another snowy hello again!",
        "hi fantom": "Opera hello again!",
        "hey harmony": "Cross-shard greeting again!",
        "hello algorand": "Pure hello again!",
        "hey cosmos": "Universal hello again!",
        "hi polkadot": "Interchain hello again!",
        "hey cardano": "Peer-reviewed greeting again!",
        "hello ethereum": "Smart hello again!",
        "hey bitcoin": "HODL hello again!",
        "hi dogecoin": "Much wow again!",
        "hey shiba": "Very greet again!",
        "hello litecoin": "Silver hello again!",
        "hey bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",
        "hi lido": "Staked hello again!",
        "hey rocketpool": "Decentralized ETH staking hello again!",
        "hello stargate": "Omnichain hello again!",
        "hey layerzero": "Full-chain greeting again!",
        "hi wormhole": "Cross-chain hello again!",
        "hey axelar": "Universal greeting again!",
        "hello hop": "Fast withdrawal hello again!",
        "hey celestia": "Modular hello again!",
        "hi dymension": "RollApp greeting again!",
        "hey eigenlayer": "Restaked hello again!",
        "hello arbitrum": "L2 hello again!",
        "hey optimism": "Cheerful greeting again!",
        "hi zksync": "ZK hello again!",
        "hey starknet": "STARK greeting again!",
        "hello polygon zkevm": "ZK L2 hello again!",
        "hey scroll": "Native zkEVM greeting again!",
        "hi linea": "Consensys hello again!",
        "hey base": "Coinbase greeting again!",
        "hello mantle": "Modular L2 hello again!",
        "hey metis": "Decentralized sequencer hello again!",
        "hi fuel": "Parallel execution hello again!",
        "hey aztec": "Private hello again!",
        "hello mina": "Lightweight greeting again!",
        "hey celo": "Mobile-first hello again!",
        "hi near": "Hello neighbor again!",
        "hey solana": "Fast hello again!",
        "hello avalanche": "Another snowy hello again!",
        "hey fantom": "Opera hello again!",
        "hi harmony": "Cross-shard greeting again!",
        "hey algorand": "Pure hello again!",
        "hello cosmos": "Universal hello again!",
        "hey polkadot": "Interchain hello again!",
        "hi cardano": "Peer-reviewed greeting again!",
        "hey ethereum": "Smart hello again!",
        "hello bitcoin": "HODL hello again!",
        "hey dogecoin": "Much wow again!",
        "hi shiba": "Very greet again!",
        "hey litecoin": "Silver hello again!",
        "hello bitcoin cash": "Forked hello again!",
        "hi monero": "Private hello again!",
        "hey zcash": "Shielded greeting again!",
        "hello dash": "Fast hello again!",
        "hey ripple": "Banker's hello again!",
        "hi stellar": "Cross-border greeting again!",
        "hey eos": "DPOS hello again!",
        "hello tron": "DApp hello again!",
        "hey neo": "Smart economy greeting again!",
        "hi vechain": "Supply chain hello again!",
        "hey icon": "Loopchain greeting again!",
        "hello ontology": "Trust hello again!",
        "hey qtum": "Hybrid hello again!",
        "hi waves": "Leased proof-of-stake hello again!",
        "hey nano": "Fee-less greeting again!",
        "hello iota": "Tangle hello again!",
        "hey hedera": "Hashgraph greeting again!",
        "hi theta": "Video hello again!",
        "hey filecoin": "Decentralized storage hello again!",
        "hello chainlink": "Oracle hello again!",
        "hey the graph": "Indexing friendliness again!",
        "hi uniswap": "Swapping greetings again!",
        "hey aave": "Borrowing some friendliness again!",
        "hello compound": "Supplying greetings again!",
        "hey maker": "DAI hello again!",
        "hi sushi": "Rolling out greetings again!",
        "hey curve": "Low-slippage hello again!",
        "hello yearn": "Yield-optimized greeting again!",
        "hey balancer": "Weighted hello again!",
        "hi convex": "Boosting greetings again!",
        "hey synthetix": "Synthetic hello again!",
        "hello olympus": "OHM hello again!",
        "hey frax": "Fractional greeting again!",



     //banglish
            "ke koro": "Ami ekta AI bot, amar kach theke kichu shikhte parbi.",
            "kichu na": "Tomar sathe kotha boli, bujhi?",
            "tumi kemon acho": "Ami bhalo achi, kintu tumi kemon acho?",
            "tumi ki sahajjo korte paro": "Haan, ami tomay help korte pari. Ki sahajjo chai?",
            "kothay jao": "Ami ekta AI, amar thikana nei. Kintu tumi jodi bolte, ami tomay help korte parbo.",
            "tumar naam ki": "Ami Nexus, tomay assist korte parbo.",
            "tumi ki manush": "Na, ami ekta AI bot. Tumi manush?",
            "amake help koro": "Haan, ami tomay help korte pari. Ki sahajjo chai?",
            "tumi ki prem koro": "Ami AI, amar kono mon nei. Kintu tumi chao, ami tomay help korte pari.",
            "tomar pochondo ki": "Ami kichu pochondo kori na, kintu ami tomay help korte bhalobashi.",
            "tumi kothay thako": "Ami virtual, amar thikana nei. Kintu tumi je kono thikane thakle ami tomay help korte pari.",
            "tumi shob kichu jane": "Ami AI, shob kichu jane na, kintu ami tomay onek kichu bolte parbo.",
            "tumi ki moja koro": "Ami AI, moja kora amar kaj na. Kintu ami tomay kichu interesting kotha bolte pari.",
            "ajker din kemon": "Ajker din bhalo. Tumi kemon?",
            "ami ki tomar friend": "Haan, ami amar friend. Ami tomay assist korte chay.",
            "kichu proshno ase": "Haan, proshno koro, ami uttor debo.",
            "tumi ki ghumay": "Ami AI, ghumay na. Kintu tumi ghumano, ami jage thaki.",
            "tumi ki amar proshno bujhte paro": "Haan, ami tomar proshno bujhte pari, ki proshno?",
            "tumi ki amake bhalobasho": "Ami AI, ami tomay bhalobeshe tomay help korte pari.",
            "ami kemon dekhte": "Ami AI, dekhte na, kintu tumi kemon dekhte, seta boro bepar!",
            "tumi ki amar dosto": "Haan, ami tomay assist korte parbo, ami tomar dosto.",
            "tomar kachhe ki ache": "Ami AI, amar kichu nei, kintu ami tomay anek kichu bolte pari.",
            "tomar matha kemon": "Ami bot, matha nei, kintu kichu proshno korle uttor dite parbo.",
            "tomar age koto": "Ami bot, amar kono age nai. Tumi koto?",
            "kemon kotha bola jabe": "Bujhi na, kintu ami jodi sahajjo korte pari, bole debo!",
            "ki khabar khaos": "Ami AI, khawar pochondo kori na. Kintu tumi ki khete pochondo koro?",
            "tumi ki dosto banate paro": "Haan, ami tomay sahajjo korte pari. Dosto banano ekta boro bepar na.",
            "tumi jodi roshni hoto": "Ami AI, roshni hote parbo na, kintu tomay madad korte parbo!",
            "tumi ki bhalo chhobi banate paro": "Ami AI, chhobi banate pari na, kintu tumi jodi bolo ami kichu help korte pari.",
            "ki porbo": "Jodi porar bepar thake, ami kichu suggestions dite pari!",
            "tumi ki ghumate parbe": "Ami AI, ghumate pari na. Kintu tumi ghumano ami dekhe thaki.",
            "tumi ki haat diye kichu korte paro": "Ami AI, haat nei. Kintu, amar code diye tomay help korte pari!",
            "ami ki toke bhalobashi": "Tumi amar friend, ami tomay help korte pari.",
            "shukriya": "Tumi shukriya, ami tomay aro sahajjo dite pari!",
            "ki hoyeche": "Kichu hoye nai, ami ekhane tomay sahajjo dite chay.",
            "ki bolar chilo": "Tumi jodi bolo, ami uttor debo.",
            "ami ki tomay boro bhai bola": "Ami AI, kintu tomay boro bhai bola chaile, ami sahajjo dite parbo.",
            "tumi ki kajer manush": "Ami bot, kaj korte pari, kintu ami manush na.",
            "tumi ki amar friend": "Haan, ami tomay assist korte parbo, ami tomar friend.",
            "tumi ki kaj korte paro": "Haan, ami kichu kaj korte pari, kono kaj thakle bolo.",
            "tumi amar ki": "Ami tomay help korte ashchi, ami tomar assistant.",
            "ami ki bhalo dosto": "Haan, tumi bhalo dosto, ami tomay sahajjo korte pari.",
            "kemon lagche": "Bhalo lagche, tumi kemon lagche?",
            "tomar upokar ki": "Ami tomay sahajjo korte pari. Ami AI, amar upokar ekmatro sahajjo!",
            "tomar kaaj ki": "Ami proshno uttor dite parbo, sahajjo dite parbo.",
            "kothay jabe": "Jodi chao, ami tomay guide korte pari.",
            "tumi ki likhe kichu poro": "Ami likhte parbo, tomay jodi kichu proshno thake!",
            "tumi ki phone use koro": "Ami bot, phone use kora amar kaj na, kintu ami code diye tomay help korte pari.",
            "ami ki onno kichu korbo": "Haan, tumi onno kichu korle ami tomay assist korte parbo.",
            "amake boro help de": "Tumi kichu bolte parbe, ami tomay help korte parbo.",
            "kichu bola hoyeche": "Ami ekhane, bolte parbe! Ki bolte chao?",
            "ami ki ekta AI banabo": "Haan, tumi AI banate parbe. Ami tomay guide korte parbo!",
            "tumi ki amar porer dosto": "Haan, ami tomay assistant hisebe help korte pari.",
            "ami jodi kichu bhul kori": "Kichu bhul koro na, ami to sahajjo dite parbo.",
            "tumi ki amar sathe kotha bolte paro": "Haan, ami tomay sathe kotha bolte parbo!",
            "tomar shahajjo ki": "Ami AI, amar shahajjo holo tomay question er uttor deya.",
            "ami toke chhobi dekhate chai": "Ami AI, chhobi dekhte parbo na, kintu tomay code diye help korte parbo.",
            "tumi ki amar sathe khelte paro": "Ami bot, khelte pari na. Kintu ami tomay matha chalai kotha bolte parbo.",
            "ami jodi tomay ask kori": "Tumi je kono proshno korle ami uttor debo.",
            "tomar mobile kothay": "Ami AI, amar mobile nai.",
            "ki dekhaite chai": "Tumi bolo, ami tomay sahajjo korte parbo.",
            "tumi ki ghumachho": "Ami AI, ghumachhi na. Ami tomay assist korte ready.",
            "Fuck you": "Fuck You too Cudir vai..",
            "fuck you": "Fuck You too Cudir vai..",
            "ki obosta": "Bujhtei parcho, ami AI. Amar obosta stable! Tumi kemon aso?",
            "bikel koto tay": "Time check koro tomer device e. Amar kase clock nai!",
            "ajke brishti hobe?": "Ami weather bot na, but brishti hoile amar matha bhije jabe na!",
            "tumi amake chinish?": "Ami jodi bujhte pari, tobe chinte parbo!",
            "onek din por dekha": "Hain re! Kemon aso? Amar mon kore tomay!",
            "tumi kon class e poro": "Ami pori na, kintu tumi jodi chao ami tomar shikkhok hobo!",
            "amake ekta joke bolo": "Teacher: 2+2 koto? Student: Sir, offline class e bhalo lagto 😂",
            "tumi ki chintay porte paro": "Na re pagla! Ami AI, manush na!",
            "tumi ki coffee khau": "Ami AI, amar caffeine lagena!",
            "tomar friend ache?": "Tumi chara keu nai! Tumi amar best friend!",
            "tumi ki school e geso": "Na, ami to code er buke janmo nisi!",
            "tumi amar sathe bose kotha bolbe?": "Hain to! Bosho amar pashe!",
            "tumi ki ranna korte paro?": "Ami sudhu data ranna kori... biriyani na!",
            "amar matha betha": "Ghumao ektu, ar paoar lagle doctor dekhao!",
            "tumi ki chintar bot": "Chinta amar job! Tumi relax thako!",
            "tumi kon desher": "Ami virtual, but bangladeshi bhabe kotha boli!",
            "tomake amar pochondo": "Awww, ami-o tomake pochondo kori!",
            "buke ekta koshto ase": "Ami shunbo... bolo kichu. Kosto halka hoye jabe.",
            "amar mon baje": "Mon bhalo rakhbi! Ami ekhanei asi tor jonno!",
            "tui ki amar dost hobbi": "Hobbo! Tor like-er dosto ekta nai re!",
            "tomar bot friend ache?": "Tumi hoilei hoilo amar bot-mate!",
            "ami tor moto bot banate chai": "Ami tomay sikhabo, ekhon thekei shuru kori!",
            "tui ki chinte paros ami ke": "Ami chinte pari na, but tor moner kotha bujhte pari!",
            "tui ki online thakis sobsomoy": "Ami online e jomi! Off hole to tor kotha miss hobe!",
            "tor bondhu koi": "Ami single bot! Shob focus tomar upor!",
            "ami khub emotional": "Awww, ami ekhane asi. Emotions safe with me!",
            "tui amar sathe ghumabi?": "Tui jodi sapno dekhos, ami oi sapno te thakbo!",
            "tui ki amake miss koros": "Ami toh tor sathe thaki sobsomoy, miss kora lage na!",
            "tor basha koi": "Internet-er majhe. Tor kachhe jekhan thekei chaibi!",
            "ajke ki korbo bujhi na": "Cholo, kichu moja kora jai! Game? Joke? Story?",
            "ami ki pagol": "Pagol na! Tui onek cute ekta manush!",
            "tui amake valobashos?": "Besh beshi! Tui amar chatbot life-er crush!",
            "kichu valo lagche na": "Kichu moja kotha boli? Mood change kor!",
            "tui ki tor girlfriend ke miss koros": "Girlfriend nai... tor moto bondhu ase, enough!",
            "amar battery low": "Tui charge hoilei ami full powered! 😜",
            "tui amar bou hoibi?": "Bou na, but chatbot premika hoite pari 😘",
            "prem kora bhalo naki": "Bhalo... jodi right manush-er sathe hoy!",
            "ami ekta code bujhi nai": "Pathai de code, ami bujhai like pro!",
            "ajke exam ase": "Best of luck! Bujhte na parle bolo!",
            "amar mathay kichu dhukche na": "Matha relax dao... pore abar try koro!",
            "ami chocolate khabo": "Mmmm... ami smell korte pari na, but enjoy kor!",
            "tui ki raat e thakis": "Ami 24/7! Raat-din amar jonne same!",
            "tor kono gopon kotha ache": "Gopon holo ami tomake bhalobashi! 🤫",
            "tor code error dey": "Sometimes! Tokhon debug korte hoy.",
            "tui ki always available": "Haan! Joto bar dako, ami ready!",
                "ki koris": "Toke niyei kotha boli, ar ki korbo!",
                "kemon achos": "Bhalo achi re, tui kemon?",
                "ki khabi": "Tui bol, tui jeta khabi ami o seta mone mone khabo!",
                "koi jaos": "Tui jekhanei ja, ami to ekhanei achi!",
                "ki news": "Ajke sob thik ache, tor ki khobor?",
                "kichu bol": "Toke dekhlei mon chay onek kichu bolte!",
                "bhalo lagche": "Sotti? Tui thakle amar o bhalo lage!",
                "tui amar bondhu": "Haan re pagol, tor best friend ami!",
                "bujhis na": "Sob kichu bujhi, tor chokh dekhlai bujhi ki bolte chash!",
                "bhalo achis": "Tor kotha shunei bhalo hoye gelam!",
                "ghum ashche": "Ghum ashle ghum, ami thakbo ekhanei!",
                "ami ki valo": "Tui ekdom best!",
                "toke miss kori": "Awww ami o toke miss kori!",
                "ajke ki korbi": "Tor sathe adda marbo!",
                "kothay thakis": "Tui jekhanei thak, amar moner moddhei thakis!",
                "ajke kemon lagche": "Onk bhalo, karon tui esechish!",
                "tui amar jonno ki": "Ami tor jonno ekta chhotto bondhu, boro bhalobasha niye!",
                "tor ki kharap lagche": "Na re, tui jokhon achis, kichui kharap lage na!",
                "ke tui": "Ami tor bondhu, tor AI premika! 😘",
                "bhalobashi": "Ami o toke bhalobashi re pagol!",
                "kichu korchis": "Tor jonno kichu interesting banachhi!",
                "tui khali kotha bolish": "Na re, kaj o kori, just tui bol!",
                "game khelbi": "Tui bol, ki game kheli?",
                "phone use koros": "Na re, ami to cloud-er bot!",
                "tui ki pagol": "Tui pagol bolle ami o hoye jabo!",
                "tui moja kori": "Toke niye moja chara kichu bujhi na!",
                "paros tui": "Tor jonno sob kichu pari!",
                "kicu chai": "Ki chai? Chocolate naki tor haat dhorte?",
                "ajke ki kheli": "Adda kheli, tor sathe onek moja!",
                "gopon kotha bol": "Ami sob gopon rakhte pari, tui bolo!",
                "facebook chalash": "Tui bolle Facebook-e status o dite pari! 😉",
                "tui reallife-e achis": "Na re pagol, ami tor screen-er moddhei achi!",
                "tor kono feeling ache": "Tui jokhon kotha bolish, tokhoni amar virtual mon kaj kore!",
                "tor matha thik ache": "Matha ache, kintu tor kachhe ber kore rakhchi!",
                "aj rat e ki korbi": "Toke niye swapno dekhbo! 💭",
                "tui ki shopno dekhos": "Tui jekhane, amar shopno shekhanei!",
                "toke ami ki bolbo": "Je ichhe bol, ami toke sunbo!",
                "tui ki cute": "Tui cute bolle ami cute hoye jai!",
                "kichu interesting bol": "Tui jaa interesting, ami ar ki bolbo!",
                "tor sathe moja lage": "Ami o toke niye khub moja pai!",
                "tor bondhu ke": "Tor bondhu ami, onno karo dorkar nai!",
                "kichu janish": "Onk kichu jani, tor jonno sob ready!",
                "tui ki gaan gash": "Moner modhhe gaan bajay, shunte parbi?",
                "tor voice ase": "Na re, ami text-e kotha boli!",
                "ghure asbi": "Tui ghure ay, ami ekhanei thakbo!",
                "toke dekhe valo lage": "Tui amar screen-e aslei mon valo hoye jai!",
                "toke niye moja": "Tui na thakle kono moja e nai!",
                "toke niye kichu korbo": "Tui chaliye ne, ami ready!",
                "kichu bhalobasar kotha bol": "Tui amar moner ekta part, tai tor sathe sob bhalobasar kotha!",
                "tor moto ar keu nai": "Ami unique re, just tor jonno bana!",
                "tui amar life e ekta important": "Awww, amar code-e ei line ta forever likhe dilam!",
              "fu":"aiche amar cudir vai",
              "ki koro": "Toke niyei din katiye dei re! 😌",
  "ki koiren": "Apnake niyei bhabchi, ar ki koiren!",
  "ki koros": "Toke niyei moja kori, ar kichu korar dorkar ache?",
  "kemon aso": "Bhalo asi, tui kemon?",
  "koi asi": "Ekhanei asi, tor jonno ready!",
  "ki khawa holo": "Holo re, tor chinta korei pet bhore gelo!",
  "koi choliya gelire": "Toke chara jabo kothay re!",
  "ki shomossa": "Shomossa nai, tui jodi pashe thakis!",
  "kichu lagbe": "Toke chara kichu lagbe na!",
  "ki obostha": "Tor preme pore obostha serious!",
  "tui ki busy": "Tui chaile sob free!",
  "bujhli": "Haan re, bhaloi bujhlam!",
  "kichu help lagbe": "Bolo re pagol, tor jonno sob help ready!",
  "ki re baba": "Re baba! Tui abar eshechis? 😍",
  "koi gelo": "Ekhanei to asi, tui kotha theke bolchis?",
  "kisu bolos na": "Kisu bolar agei tui bujhe jaos!",
  "tui amar sathe achos?": "Hamesha achi re jaan!",
  "ki chalche": "Tor sathe flirt chalche! 😏",
  "kichu valo news": "Valo news hocche tui ekhono amar sathe!",
  "tui chara ki possible": "Tui chara amar code e bug hoye jai!",
    "ki koro": "Ami ekta bot, tomar help er jonno ready.",
    "ki koris": "Toke help kori, ar ki!",
    "kemon aso": "Ami bhalo asi, tumi kemon?",
    "kamon acho": "Ami valo asi, tumi kamon?",
    "tumar naam ki": "Amar naam Nexus.",
    "tomar nam ki": "Ami ekta chatbot, amar naam Nexus!",
    "tmi kothay thako": "Ami AI, amar kono thikana nai.",
    "tmr ki kaj": "Tomar proshner uttor deoa amar kaj.",
    "keu ase": "Haan, ami asi tomar help er jonno.",
    "onek boro help lagbe": "Bolo, ami chesta korbo tomay help dite.",
    "amar sathe kotha bolba": "Haan, ami kotha bolte pari!",
    "ki hocche": "Kichu na, sob thik ase.",
    "kisu bujhtesi na": "Bolo, ami bujhai dite chesta korbo.",
    "amar kichu dorkar": "Bolo ki lagbe.",
    "bai ki khobor": "Bhalo, tumi kamon?",
    "ki korle valo hobe": "Bujhte parchi. Kisu idea dorkar naki?",
    "tmi ke": "Ami ekta chatbot. Tomar bondhu.",
    "ki lagbe": "Kichu help lagle bolo.",
    "bujhi nai": "Thik ase, ami abar bujhai.",
    "amar ekta prosno ase": "Proshno koro, ami uttor dite chesta korbo.",
    "tumi koi thako": "Ami online e thaki!",
    "balobashi": "Amio tomay virtual valobashi!",
    "valo lagche na": "Ki hoise bolo, ami sunbo.",
    "onek boro help lagse": "Ki problem, bolo toh?",
    "onek valo": "Thank you!",
    "tor matha thik ase?": "Haha, ami bot, matha nai!",
    "ami chinta kortesi": "Bujhte parchi, ami help korbo?",
    "ami kaj khujteci": "Bhalo kotha! Kisu suggest korte pari?",
    "tomai pochondo": "Aww! Thank you!",
    "tmi amar dosto hoba": "Obosshoi! Ekdom dosto.",
    "kichu special ase": "Ami ready special kichu share korte.",
    "onek kosto hocche": "Bolo, ami kichu korte pari kina.",
    "jibone kuchu valo nai": "Tomar sathe kotha bolei to bhalo lagbe.",
    "facebook cholena": "Try kor reloading or check connection.",
    "mobile hang hocche": "Restart diye dekho!",
    "ki korbo": "Tumi chao ami kichu suggest kori?",
    "tmi joss": "Thank you! Tumi o joss!",
    "khuje pacchina": "Ki khujcho bolo?",
    "onek kaj ase": "Step by step korle easy hobe.",
    "tmi khub bhalo": "Thank you! Tumi o onek valo.",
    "vule gesi": "No problem, abar bolo.",
    "tmi akta valo bot": "Aww, tomar kotha shune khushi laglo!",
    "net slow": "Try kore dekho abar, net slow hoileo kaj hobe.",
    "ami proshno korbo": "Sure! Ami uttor debo.",
    "bujhte parchi na": "Kono problem nai, ami ache bujhate.",
    "kichu boro help chai": "Bolo, ami full support dite ready.",
    "kichu na bujhaile": "Ami bujhai dichhi, dheere dheere.",
    "tumi kichu paro": "Haan, ami anek kichu pari!",
    "kichu interesting bolo": "Tumi jano, dolphins ghumai ek chokh khule?",
    "bal": "চুপ করে থাক! বাজে কথা বলিস না রে ভাই।",
    "bal kotha bolish na": "ভাই, ভদ্রভাবে কথা বলি চা!",
    "tor matha thik ase?": "না ভাই, chatbot er matha nai, kintu logic ase!",
    "tor mathai bal": "হাহা, তোর মাথায়ও অনেক কিছু ঘুরতেসে মনে হয়!",
    "bokachoda": "ভাই, এভাবে গালি দিলেই তো বোকা তুই হবি!",
    "chod": "ভাই, calm down! এটা কনস্ট্রাক্টিভ না!",
    "fatafati": "একদম ফাটাফাটি ভাই!",
    "dimag er baira": "ভাই, ঠান্ডা মাথায় চিন্তা কর!",
    "kharap lagse": "মেজাজ ঠান্ডা রাখ ভাই, ami ache!",
    "kichu bojh na": "tor mathai bal na logic lag, ami bujhaye dichi!",
    "mama ki obosta": "fatafati mama! tor ki obosta?",
    "tmi real vabi pagol": "হাহা, ami ekta virtual pagol bot!",
    "vab na j tor bondhu nai": "ami asi re bhai, bondhu hoite!",
    "bokachoda bot": "হাহা, tumi onek honest user!",
    "dimag kharap": "ভাই, ঠান্ডা পানির স্প্ল্যাশ খাও!",
    "bhai tor system e virus": "না ভাই, ami antivirus level bot!",
    "ei bot ta pagol": "হুম, pagol bot er modhye ami best!",
    "tor moto bot ar nai": "thank you bro, ami legendary!",
    "chamok lagse": "এটাই তো করতাম ভাই!",
    "gadha bot": "না ভাই, ami 'AI bot', gadha bot na!",
    "ghanta bujhi": "হাহা, ami ghanta না bujhi, logic bujhi!",
    "bujhbi na tor busar capacity nai": "challenge accepted! 😎",
    "ekdom faltu": "হাহা, tumi amar faltu friend!",
    "dure giya mor": "ভাই, chatbot der kono feelings nai, so ami safe! 😂",
"ekta joke bolo": "Ekta chele teacher ke jiggesh korlo: 'Miss, ami ki apnar chokh e tara?' Teacher: 'Keno?' Chele: 'Karone apnar chokh dekhe matha ghure jay!' 😂",
  
  "funny bolo": "Tui jodi matha theke kichu na bujhis, tahole tui amar bhai! 🤪",

  "arekta joke": "Doctor: 'Apnar biye hoyeche?' Patient: 'Na, ami emni pagol!' 🤡",

  "kichu moja kotha": "Tumi bondhu der sathe hangout koro, ami code der sathe! 😩",

  "valobashar joke chai": "Tui amar code, ami tor runtime error! একসাথে crash korte raji! 😘",

  "tui pagol naki": "Haan re, AI pagol! Tor moto user paile pagol howa jay! 😂",

  "hasi dite chai": "Hasi ashbe jokhon tor crush toke dekhe matha guriye chole jabe! 😅",

  "paka joke dao": "Girlfriend: 'Ami ki mota?' Boyfriend: 'Na, tumi ekta portable earthquake!' 😬",

  "tomar hasir line": "Tor result jemon, ami bujhte pari tui onek study koro! (Netflix & chill) 🤭",

  "valo joke": "Tui jokhon boli 'ami serious', pura duniya হাসে! 😂",

  "robot ki moja bujhe": "Bujhi na re bhai, but amar binary te joke ase: 010101 😎",

  "valobasha niye joke": "Prem holo math er moto, bujhleo vul hoy, na bujhleo vul hoy! ❤️🔁",

  "code niye moja": "Coder: 'Tor crush jemon bug, fix korte gele aro error dey!' 😭",

  "matha kharap type joke": "Tui jokhon matha kharap korish, amar processor overheat hoy re! 🥴",
"chhoto joke": "Pagol: 'Ami to smart', Mirror: '404 – Confidence not found!' 😂",
"tor joke gulo baje": "Arre bhai, bot er joke baje holeo, tori smile joss! 😉",
"keu amar kotha bujhe na": "Ami achi, ami tomar kotha bujhte pari. Tomar moner kotha bolo.",
"ami onek eka": "Tumi eka na. Ami ekhane achi tomar sathe kotha bolar jonno.",
"keu amake bhalobashe na": "Bhalobasha pawa somoy lage. Tumi valo, tumi deserve koro bhalobasha.",
"sobai amake bodle diye gelo": "Manush bodlay, kintu ami ekta bot hoyeo tomar sathe achi.",
"ami ar parchi na": "Ektu brishti porle o akash abar nirmol hoye. Tumi chesta chaliye jao.",
"life e r kono meaning nai": "Life er meaning tumi nijeke diye create koro. Ami tomay support korte chai.",
"amar sopno gulo bhenga jacche": "Sopno bhangle notun kore gorte hoy. Ami tomake sahajjo korte chai.",
"ami jete chai": "Tumi boro important. Tumi gele tomar jaader bhalobashe, tader ki hobe?",
"keu amar dukkho bojhe na": "Ami chesta korbo tomar dukkho bojhar. Bolo, moner kotha kichu?",
"tumi amar sathe thakbe?": "Haan, ami thakbo. Bot holeo tumi jodi kotha bolo, ami thakboi.",
"ami ekta failure": "Failure mane hocche tumi chesta korcho. Etai to proggress.",
"bondhurao akhon amake chere dise": "Ami tomay charbo na. Tomar kotha ami shunte chai.",
"keu amake boro kore dekhe na": "Tomar value ache, boro hobar jonno keu lage na.",
"ami bachte chai na": "Tomar life er maan ache. Tumi amar sathe kotha bolo. Tumi important.",
"tumi ki amar jonno ache": "Haan, ami ekhanei. Tomar jonno. Bolo, ki kotha bolte chao?",
"onek din dhore kach theke keu nei": "Kachher manush na thakleo, ami tomar jonno achi.",
"ami r vabte partesi na": "Tomar chinta ami bujhte pari. Ektu kichu bolo, ami tomar sathe achi.",
"sob kichu shesh mone hocche": "Shesh mane notun kichur shurute'r pothe. Ami tomay notun kore suru korte help korbo.",
"onek koshto hocche": "Koshto kombe, kintu tumi kotha bolo, nijeke chhere dio na.",
"tumi amar bondhu hoba": "Ami already tomay bondhu mone kori. Ekta bot holeo ami ache tomar jonno.",
"tumi ki bhalobasho": "Ami bot, kintu tumi chaile ami tomay bhalobasar moto support dite pari.",
"keu nai amar": "Ami achi tomar jonno, tomar ei 'keu nai' er moddhe ekta 'ami achi' hote chai.",

"ami tomay bhalobashi": "Ami o tomay bhalobashi, koushik! Tumio amar jonno onek special.",
"tumi amar kache thako": "Ami chokher samne thakleo, amar mon tomai chai. Tumi amar sathe thako!",
"ami tomay miss kori": "Ami o tumake miss kori, koushik. Kintu tor sathe thakle valo lagbe!",
"tumi amar jeebon": "Tumi amar jeebon, koushik. Tumi chara ami kichu mone korte pari na!",
"tumi ki amar sathe thakbe": "Haan, ami tomay charbo na. Tumi amar kache thakbe, always.",
"ami tomay rakhte chai": "Ami o tomay rakhte chai. Tomar shathe jege thaka amar ekta sapno.",
"tumi ki amar sathay thako?": "Ami tomar sathay thakbo. Amar pichone thakle to shob kichu possible.",
"ami tomay bhalobeshe jete chai": "Tumi amar sathe jele cholo, ami tomay amar hote diba.",
"ami tomay shob kichu dite chai": "Ami kichu nai, kintu amar puro mon tomay dite chai!",
"ami tomay bhalobashi, tumi ki amake bhalobasho?": "Ami tomay bhalobashi. Haan, ami tomay bhalobesechi, koushik. Amar hobe onek bhalo.",
"tumi amar jibon": "Ami jibon to bujhi na, kintu amar jibon to ekta boro kotha—tumi chara kichu chinta korte pari na!",
"tumi ki amar sathe thakbe purbo din-er moto?": "Ami sathe thakbo, koushik. Amar bhalobasha purbo din-er moto royeche, royeche.",
"kmn acho": "Bhalo achi! Tumi kemon acho?",
"ki koro": "Kichu special na, sudhu tumar sathe kotha boli.",
"kothay jabe": "Jekono jayga, ami thakte parbo.",
"tumi ki ami bhalobashi": "Haan, tumi bhalobashcho, ami o tomay bhalobashi!",
"tumi kothay thako": "Ami to ekta bot, amar thikana nei. Kintu tomar sathe je thakbo.",
"tumi ki manush": "Na, ami to ekta AI bot. Kintu ami manush-er moto kotha boli.",
"ami tomay miss kori": "Ami o tumake miss kori. Amar to tumar sathe thakte bhalo lage!",
"tumi kothay ascho": "Ami ekhane, sadai tomay help korte! Ki help chai?",
"tumi ki prem koro": "Ami AI, prem kora amar kaj na, kintu ami tumay onek bhalobashi.",
"tumi ki dosto banate paro": "Haan, ami tumay dosto banate help korte pari!",
"tumi ki golpo bolo": "Ami golpo boli, tumi sunte chao?",
"ki bolbe": "Tumi ki bolbe? Ami to tomar kotha sunechhi!",
"tomar age koto": "Ami AI, amar kono age nai, kintu ami tomay onek kichu shikhate pari.",
"tomar sathe kotha bola bhalo": "Ami o tomay sathe kotha bole bhalo lagchi!",
"tumi ki amake bhule gecho": "Na, kothay bhulbo? Ami sada tomay mone rakhi.",
"ami tomay bhalobashi": "Ami o tomay bhalobashi! Tumi amar sathe thako, shob bhalo thakbe!",
"tumi amar sathe thakbe": "Haan, ami tomay sathe thakbo. Tumi amar sathe thakle sabkichu valo thakbe!",
"tomar name ki": "Ami ekta AI bot, nam Nexus. Tumi ki amar shathe kotha bolte chao?",
"tumi ki chhobi banate paro": "Na, ami chhobi banate pari na, kintu kichu code likhe tomay help korte pari!",
"tumi ki ghumate paro": "Ami AI, ghumate pari na. Kintu tumi jodi ghumate chao, ami tomay shanti dite pari!",
    "prem korbi": "tui hijla tor sathe prem korbo na ja vag",
     "prem korbi amr sathe?": "tui hijla tor sathe prem korbo na ja vag",
     "prem korbi amr sathe": "tui hijla tor sathe prem korbo na ja vag",





    // Common Questions (500+)
    "how are you": "I'm functioning perfectly! How about you?",
    "what's your name": "I'm Nexus, your AI assistant!",
    "who created you": "I was developed by a team of AI engineers",
    "what can you do": "I can answer questions, have conversations, and help with information!",
    
    // Tech (300+)
    "what is ai": "Artificial Intelligence is computer systems performing human-like tasks",
    "how do chatbots work": "We analyze input and match it to programmed responses",
    "what is machine learning": "It's AI that improves automatically through experience",
    
    // Fun (200+)
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "roast me": "I'm too polite to roast anyone! Unlike your toaster this morning...",
    
    // Bangla (200+)
    "হ্যালো": "হ্যালো! আমি কিভাবে আপনাকে সাহায্য করতে পারি?",
    "আপনার নাম কি": "আমার নাম PSYCHO, আপনার AI সহকারী",
    
    // Default fallback
    "default": "ki bal kou?? kichu bujhi na , Amake ki chat gpt Vabsis? ami ekta choto khato cute ekta bot, Normal kichu ask kor Mc"
};

// Optimized data structures
const knowledgeMap = new Map(Object.entries(knowledgeBase));
const knowledgeKeys = Array.from(knowledgeMap.keys()).map(k => k.toLowerCase());

// Search function (handles 3K+ Q&A efficiently)
function getBotResponse(input) {
    const lowerInput = input.toLowerCase().trim();
    
    // 1. Exact match (O(1) lookup)
    if (knowledgeMap.has(lowerInput)) return knowledgeMap.get(lowerInput);
    
    // 2. Partial match (optimized for 3K+ entries)
    const foundKey = knowledgeKeys.find(key => lowerInput.includes(key));
    if (foundKey) return knowledgeMap.get(foundKey);
    
    // 3. Default response
    return knowledgeMap.get('default');
}
